preset: psr2

enabled:
  - phpdoc_add_missing_param_annotation
  - phpdoc_annotation_without_dot
  - phpdoc_link_to_see
  - phpdoc_no_access
  - phpdoc_no_package
  - phpdoc_order
  - phpdoc_scalar
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - phpdoc_var_without_name

finder:
  exclude:
    - "features"
