language: php

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer install
  - php -S localhost:8000 -t public &> /dev/null &
  - php vendor/bin/doctrine orm:schema-tool:create

script:
  - composer test

matrix:
  allow_failures:
    - php: 7.1
    - php: nightly
