language: php

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - cp .env.travis .env
  - composer install
  - php -S localhost:8000 -t public &> /dev/null &
  - php vendor/bin/doctrine orm:schema-tool:create

script:
  - composer test:coverage
  - composer test:acceptance

after_success:
  - php vendor/bin/coveralls -v -x tests/_output/coverage.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.1
    - php: nightly
