language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - psql -c 'create database sihae;' -U postgres
  - composer install
  - cp .env.travis .env
  - php artisan migrate

script:
  - npm test

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
